### ISSUE TITLE
OpenCV 4.7 OutOfMemoryError'

### ISSUE THREAD

**Issue by 1107979819** [Jaron0211/VINS-Fusion-gpu-cv4#1]
` rosrun vins vins_node src/VINS-Fusion-gpu-cv4/config/euroc/euroc_mono_imu_config.yaml `

logs:
`rosrun vins vins_node src/VINS-Fusion-gpu-cv4/config/euroc/euroc_mono_imu_config.yaml 
[ INFO] [1683299738.564487583]: init begins
config_file: src/VINS-Fusion-gpu-cv4/config/euroc/euroc_mono_imu_config.yaml
USE_IMU: 1
IMU_TOPIC: /imu0
result path /home/tony-ws1/output//vio.csv
[ WARN] [1683299738.582543150]:  fix extrinsic param 
camera number 1
[ INFO] [1683299738.585384678]: Synchronized sensors, fix time offset: 0
[ INFO] [1683299738.585450152]: ROW: 480 COL: 752 
 exitrinsic cam 0
 0.0148655  -0.999881  0.0041403
  0.999557  0.0149672  0.0257155
-0.0257744 0.00375619   0.999661
-0.0216401  -0.064677 0.00981073
set g       0       0 9.81007
[ INFO] [1683299738.585657167]: reading paramerter of camera src/VINS-Fusion-gpu-cv4/config/euroc/cam0_mei.yaml
MULTIPLE_THREAD is 1
[ WARN] [1683299738.586280386]: waiting for image and imu...
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.7.0) /home/drone/opencv-4.7.0/modules/core/src/alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 342986660313600 bytes in function 'OutOfMemoryError'

Aborted (core dumped)
`

**Comment by Jaron0211** [comment]
1. Make sure you make the opencv with CUDA enable
2. rebuild the cv_bridge in ROS
3. rebuild the VINS-Fusion-gpu

I think those steps could fix the problem, good luck.
